resource_types:
- name: terraformtype
  type: docker-image
  source:
    repository: ljfranklin/terraform-resource
    tag: "1.4.6-11d9d59"

resources:
  - name: webfe-tf
    type: terraformtype
    check_every: never
    source:
      #env_name: staging
      backend_type: s3
      backend_config:
        bucket: adm-monitor-demo-s3bucket
        key: adm/webfe-terraform.tfstate
        region: eu-west-2
        access_key: ((aws_access_key))
        secret_key: ((aws_secret_key))
      vars:
        tag_name: concourse
      env:
        AWS_ACCESS_KEY_ID: ((aws_access_key))
        AWS_SECRET_ACCESS_KEY: ((aws_secret_key))

  - name: wrapper-tf
    type: terraformtype
    check_every: never
    source:
      #env_name: staging
      backend_type: s3
      backend_config:
        bucket: adm-monitor-demo-s3bucket
        key: adm/wrapper-terraform.tfstate
        region: eu-west-2
        access_key: ((aws_access_key))
        secret_key: ((aws_secret_key))
      vars:
        tag_name: concourse
      env:
        AWS_ACCESS_KEY_ID: ((aws_access_key))
        AWS_SECRET_ACCESS_KEY: ((aws_secret_key))

  - name: cpu-checker-tf
    type: terraformtype
    check_every : never
    source:
      #env_name: staging
      backend_type: s3
      backend_config:
        bucket: adm-monitor-demo-s3bucket
        key: adm/cpu-checker-terraform.tfstate
        region: eu-west-2
        access_key: ((aws_access_key))
        secret_key: ((aws_secret_key))
      vars:
        tag_name: concourse
      env:
        AWS_ACCESS_KEY_ID: ((aws_access_key))
        AWS_SECRET_ACCESS_KEY: ((aws_secret_key))


  - name: web-fe-repo
    type: git
    icon: github
    source:
      uri: https://github.com/mcguinnessa/monitor-demo
      branch: main

  - name: md-mongo-wrapper-repo
    type: git
    icon: github
    source:
      uri: https://github.com/mcguinnessa/md-mongo-wrapper
      branch: main

  - name: cpu-checker-repo
    type: git
    icon: github
    source:
      uri: https://github.com/mcguinnessa/demo-cpu-checker
      branch: main

jobs:
- name: webfe-tf-plan
  public: true
  serial: true
  plan:
  - get: web-fe-repo
  - task: check-source
    config:
      platform: linux
      image_resource:
        type: docker-image
        source:
          repository: alpine
      inputs:
      - name: web-fe-repo
      run:
        path: /bin/sh
        args:
        - -c
        - |
          ls -lrt
          pwd
          cd web-fe-repo/terraform
          pwd
          ls -lrt
          env

  - put: webfe-tf
    params:
      env_name: staging
      terraform_source: web-fe-repo/terraform
      plan_only: true
      vars:
        subnet_cidr: 10.0.1.0/24

- name: webfe-tf-destroy
  plan:
  - get: web-fe-repo
    trigger: false
    passed: [webfe-tf-plan]
  - get: webfe-tf
    trigger: true
    passed: [webfe-tf-plan]
  - put: webfe-tf
    params:
      env_name: staging
      terraform_source: web-fe-repo/terraform
      action: destroy
    get_params:
      action: destroy

########################################################################################################
#
# WRAPPER
#
########################################################################################################

- name: wrapper-tf-plan
  public: true
  serial: true
  plan:
  - get: md-mongo-wrapper-repo
  - task: check-source
    config:
      platform: linux
      image_resource:
        type: docker-image
        source:
          repository: alpine
      inputs:
      - name: md-mongo-wrapper-repo
      run:
        path: /bin/sh
        args:
        - -c
        - |
          ls -lrt
          pwd
          cd md-mongo-wrapper-repo/terraform
          pwd
          ls -lrt
          env

  - put: wrapper-tf
    params:
      env_name: staging
      terraform_source: md-mongo-wrapper-repo/terraform
      plan_only: true
      vars:
        subnet_cidr: 10.0.1.0/24

- name: wrapper-tf-destroy
  plan:
  - get: md-mongo-wrapper-repo
    trigger: false
    passed: [wrapper-tf-plan]
  - get: wrapper-tf
    trigger: true
    passed: [wrapper-tf-plan]
  - put: wrapper-tf
    params:
      env_name: staging
      terraform_source: md-mongo-wrapper-repo/terraform
      action: destroy
    get_params:
      action: destroy


########################################################################################################
#
# CPU CHECKER
#
########################################################################################################
- name: cpu-checker-tf-plan
  public: true
  serial: true
  plan:
  - get: cpu-checker-repo
  - task: check-source
    config:
      platform: linux
      image_resource:
        type: docker-image
        source:
          repository: alpine
      inputs:
      - name: cpu-checker-repo
      run:
        path: /bin/sh
        args:
        - -c
        - |
          ls -lrt
          pwd
          cd cpu-checker-repo/terraform
          pwd
          ls -lrt
          env

  - put: cpu-checker-tf
    params:
      env_name: staging
      terraform_source: cpu-checker-repo/terraform
      plan_only: true
      vars:
        subnet_cidr: 10.0.1.0/24

- name: cpu-checker-tf-destroy
  plan:
  - get: cpu-checker-repo
    trigger: false
    passed: [cpu-checker-tf-plan]
  - get: cpu-checker-tf
    trigger: true
    passed: [cpu-checker-tf-plan]
  - put: cpu-checker-tf
    params:
      env_name: staging
      terraform_source: cpu-checker-repo/terraform
      action: destroy
    get_params:
      action: destroy





